import { useMemo } from "react";
import { useMonteCarloStore } from "../../strategy/monteCarlo/monteCarloStore";
import {
  buildLossStreakMatrix,
  DEFAULT_LOSS_STREAK_LENGTHS,
  DEFAULT_LOSS_STREAK_WIN_RATES,
  LOSS_STREAK_SEQUENCE_LENGTH_PRESETS,
} from "../../strategy/monteCarlo/lossStreak";
import "./panels.css";
import "./DetailedAnalysis.css";
import "./MonteCarlo.css";

/**
 * LOSING STREAK PROBABILITY - a pure ANALYTICAL table (lossStreak.ts's DP
 * recurrence), deliberately rendered WITHOUT a "Run" button or progress
 * bar: it recomputes live on every control change (sub-100ms even at the
 * largest sequence-length preset), which is itself the UI signal that this
 * is not a Monte Carlo simulation - per spec's "The UI should not falsely
 * imply that this table is necessarily generated by Monte Carlo."
 * Completely independent of RR, risk %, account balance, or the Strategy
 * Lab/Challenge state elsewhere on this page.
 */
export function LossStreakMatrix() {
  const sequenceLength = useMonteCarloStore((s) => s.lossStreakSequenceLength);
  const setSequenceLength = useMonteCarloStore((s) => s.setLossStreakSequenceLength);

  const matrix = useMemo(
    () => buildLossStreakMatrix({ winRatesPct: DEFAULT_LOSS_STREAK_WIN_RATES, sequenceLength, streakLengths: DEFAULT_LOSS_STREAK_LENGTHS }),
    [sequenceLength]
  );

  return (
    <div className="da-card">
      <div className="da-card-header">
        <span className="da-widget-title">Losing Streak Probability</span>
        <div className="strategy-row mc-heatmap-controls">
          <label className="strategy-label">Trade Sequence Length</label>
          <select className="strategy-input" value={sequenceLength} onChange={(e) => setSequenceLength(Number(e.target.value))}>
            {LOSS_STREAK_SEQUENCE_LENGTH_PRESETS.map((n) => (
              <option key={n} value={n}>
                {n.toLocaleString()}
              </option>
            ))}
          </select>
        </div>
      </div>
      <p className="panel-dim mc-heatmap-caption">
        Probability of at least X consecutive losses within {sequenceLength.toLocaleString()} trades - a closed-form calculation, not a
        simulation.
      </p>
      <div className="mc-heatmap-scroll">
        <table className="mc-heatmap-table">
          <thead>
            <tr>
              <th className="mc-heatmap-corner">Win Rate ↓ / Streak →</th>
              {DEFAULT_LOSS_STREAK_LENGTHS.map((x) => (
                <th key={x}>{x}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {matrix.winRatesPct.map((wr, rowIdx) => (
              <tr key={wr}>
                <th scope="row">{wr}%</th>
                {matrix.probabilities[rowIdx].map((pct, colIdx) => (
                  <td
                    key={colIdx}
                    className="mc-heatmap-cell"
                    style={{ background: `color-mix(in srgb, var(--danger) ${pct}%, var(--ok))` }}
                    title={`WR ${wr}%, streak >= ${DEFAULT_LOSS_STREAK_LENGTHS[colIdx]}: ${pct.toFixed(1)}%`}
                  >
                    {pct >= 99.95 ? "100%" : pct < 0.05 ? "0%" : `${pct.toFixed(1)}%`}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
